[project]
name = "qgarage"
version = "2.1.3"
description = "A QGIS plugin framework for installing and running isolated mini-tools with per-app uv or pixi environments."
readme = "README.md"
authors = [
    { name = "Matt Adams" }
]
requires-python = ">=3.9"
dependencies = [
    "pytest>=8.4.2",
]

[tool.ruff]
line-length = 88
format.docstring-code-format = true
lint.select = ["A", "C4", "E4", "E7", "E9", "F", "FLY", "FURB", "I", "PLE", "PT", "RUF", "SIM", "UP", "I002"]
lint.ignore = ["SIM108", "SIM105"]
lint.per-file-ignores."tests/**" = ["RUF059"]
lint.per-file-ignores."!tests/**/*.py" = ["PT"]
# Tell Ruff exactly what to enforce and clean up
lint.isort.required-imports = ["from __future__ import annotations"]


[tool.uv]
link-mode = "symlink"

[dependency-groups]
dev = [
    "prek>=0.3.8",
    "ruff>=0.15.8",
]
